import img from '../images/movie.jpg';

export const movies = [
  {
    id: 1,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 2,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
  {
    id: 3,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 4,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
  {
    id: 5,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 6,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
  {
    id: 7,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 8,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
  {
    id: 9,
    name: '33 слова о дизайне',
    image: img,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 10,
    name: '33 слова о дизайне',
    image: img,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
  {
    id: 11,
    name: '33 слова о дизайне',
    image: img,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 12,
    name: '33 слова о дизайне',
    image: img,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
  {
    id: 13,
    name: '33 слова о дизайне',
    image: img,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 14,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
  {
    id: 15,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 16,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
  {
    id: 17,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 18,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
  {
    id: 19,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 20,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
  {
    id: 21,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: true,
  },
  {
    id: 22,
    name: '33 слова о дизайне',
    image: img,
    duration: 200,
    trailerLink: "https://www.youtube.com/watch?v=ecpqKUE0DpU",
    saved: false,
  },
]

export const devises = {
  desktop: {
    width: 1023,
    movies: {
      default: 12,
      more: 3,
    },
  },
  tablet: {
    width: 767,
    movies: {
      default: 8,
      more: 2,
    },
  },
  mobile: {
    width: 320,
    movies: {
      default: 5,
      more: 2,
    },
  },
};
